# Site settings
title: devbymike.github.io
email: mike@mk3y.com
description: "experimental github blog"
baseurl: ""
url: "https://devymike.github.io"
twitter_username: mike_key
github_username:  devbymike

# Build settings
markdown: kramdown
permalink: pretty
excerpt_separator: "<!-- more -->"

gems:
  - jekyll-sitemap